name: Build K40 Whisperer Docker Container

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * WED'

jobs:
  build:
    name: Build K40 Whisperer Docker Container
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Bake our Containers
        uses: docker/bake-action@v2.1.0
        with:
          files: bake.hcl
          push: true
